version: '3'
services:
  db:
    image: postgres:11.5-alpine
     ports:
      - '5432:5432'
     environment:
       POSTGRES_PASSWORD: changeme
       POSTGRES_DB: candydb
       POSTGRES_USER: candy


  backend:
    build:
      context: .
      dockerfile: ./docker/backend/Dockerfile
    environment:
      - APP_ENV=dev
    depends_on:
     - db
    ports:
      - "40001:40001"
    volumes:
     - .:/code


  frontend:
    build:
      context: .
      dockerfile: ./docker/frontend/Dockerfile
    environment:
      - APP_ENV=dev
      - APP_BACKEND_URL=backend:40001
      - APP_FRONTEND_PORT=40002
    depends_on:
      - backend
    ports:
      - "40002:40002"
    volumes:
      - ./frontend:/app/src